export const LOAD_PATIENT_SUCCESS = 'LOAD_PATIENT_SUCCESS';
export const LOAD_PATIENT_FAILURE = 'LOAD_PATIENT_FAILURE';

export const LOAD_MEDICATIONS_SUCCESS = 'LOAD_MEDICATIONS_SUCCESS';
export const LOAD_MEDICATIONS_FAILURE = 'LOAD_MEDICATIONS_FAILURE';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

